[build-system]
requires = [
  "setuptools>=70",
  "setuptools_scm>=7",
  "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "aie4ml"
dynamic = ["version"]
description = "AMD AIE backend plugin for hls4ml"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
  { name = "Dimitrios Danopoulos", email = "dimitrios.danopoulos@cern.ch" },
]
requires-python = ">=3.10"

keywords = [
  "hls4ml",
  "aie",
  "amd",
  "fpga",
  "backend",
  "AI engine",
]

classifiers = [
  "Development Status :: 3 - Alpha",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3 :: Only"
]
dependencies = [
   "jinja2>=3.0"
]

[project.optional-dependencies]
testing = [
  "pytest>=7.0",
  "keras",
  "qkeras",
]

[project.urls]
Homepage = "https://github.com/dimdano/aie4ml"
Issues = "https://github.com/dimdano/aie4ml/issues"

[project.entry-points."hls4ml.backends"]
AIE = "aie4ml.plugin:register"

[tool.setuptools]
package-dir = { "" = "src" }
include-package-data = true

[tool.setuptools.packages.find]
where = [ "src" ]

[tool.setuptools_scm]
write_to = "src/aie4ml/_version.py"

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py310"

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.ruff.lint]
select = ["E", "F", "I", "W"]
ignore = []
fixable = ["ALL"]
unfixable = []

[tool.pytest.ini_options]
markers = [
  "aie_ir: tests that exercise the hls4ml AIE backend",
  "requires_vitis: requires AMD Vitis installation",
]
